
// Ceruela Coffee Shop coffee data
export const ceruelaCoffees = [
    {
      id: 1,
      name: "Ceruela Signature Blend",
      description: "Our signature house blend with notes of dark chocolate, caramel, and a hint of orange zest.",
      price: 850,
      roast: "Medium-Dark",
      origin: "House Blend",
      rating: 4.9,
      reviews: 156,
      inStock: true,
      isFeatured: true,
      tags: ["Signature", "Best Seller"],
      weight: "250g"
    },
    {
      id: 2,
      name: "Ceruela Morning Roast",
      description: "Light roast with bright citrus notes and floral aroma. Perfect for your morning cup.",
      price: 750,
      roast: "Light",
      origin: "Ethiopia",
      rating: 4.7,
      reviews: 124,
      inStock: true,
      isFeatured: true,
      tags: ["Morning", "Single Origin"],
      weight: "250g"
    },
    {
      id: 3,
      name: "Ceruela Dark Reserve",
      description: "Bold and intense dark roast with smoky notes and low acidity. Our strongest offering.",
      price: 950,
      roast: "Dark",
      origin: "Sumatra",
      rating: 4.8,
      reviews: 89,
      inStock: true,
      isFeatured: true,
      tags: ["Dark Roast", "Intense"],
      weight: "250g"
    },
    {
      id: 4,
      name: "Ceruela Velvet Espresso",
      description: "Smooth espresso blend with velvety crema and notes of toasted nuts and dark berries.",
      price: 900,
      roast: "Dark",
      origin: "Espresso Blend",
      rating: 4.6,
      reviews: 112,
      inStock: true,
      isFeatured: false,
      tags: ["Espresso", "Smooth"],
      weight: "250g"
    },
    {
      id: 5,
      name: "Ceruela Colombian Select",
      description: "Single-origin Colombian beans with balanced body and notes of caramel and red apple.",
      price: 800,
      roast: "Medium",
      origin: "Colombia",
      rating: 4.5,
      reviews: 78,
      inStock: true,
      isFeatured: false,
      tags: ["Single Origin", "Balanced"],
      weight: "250g"
    },
    {
      id: 6,
      name: "Ceruela Decaf Harmony",
      description: "All the flavor of our signature blend without the caffeine. Swiss water processed.",
      price: 850,
      roast: "Medium",
      origin: "Decaf Blend",
      rating: 4.4,
      reviews: 67,
      inStock: true,
      isFeatured: false,
      tags: ["Decaf", "Swiss Water"],
      weight: "250g"
    },
    {
      id: 7,
      name: "Ceruela Brazilian Gold",
      description: "Sweet and nutty Brazilian beans with low acidity and smooth chocolate finish.",
      price: 750,
      roast: "Medium",
      origin: "Brazil",
      rating: 4.3,
      reviews: 56,
      inStock: true,
      isFeatured: false,
      tags: ["Single Origin", "Sweet"],
      weight: "250g"
    },
    {
      id: 8,
      name: "Ceruela Seasonal Limited",
      description: "Special limited edition roast featuring seasonal beans from exclusive farms.",
      price: 1200,
      roast: "Light-Medium",
      origin: "Seasonal Blend",
      rating: 4.9,
      reviews: 45,
      inStock: true,
      isFeatured: true,
      tags: ["Limited Edition", "Seasonal"],
      weight: "250g"
    },
  ];